CREATE TABLE public.item (
                             id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             item_name varchar(10) NULL,
                             price int4 NULL,
                             quantity int4 NULL,
                             CONSTRAINT item_pk PRIMARY KEY (id)
);